### PR TITLE
Set align of last item of menu

### PR DESCRIPTION
**Pull request by MJuhas**

### CODE REVIEW

**Comment by buksy90** [comment]
what issue were you working on ? What is the goal of this changes?

**Comment by MJuhas** [comment]
I repaired align of last item of menu to right, just show in mobil screen

**Comment by MJuhas** [comment]
#24

**Comment by buksy90** [comment]
why are there changes in upcomingMatches and newsList?

**Comment by MJuhas** [comment]
It is that because, when I wanted push branch "FixMenu" , that " git" wrote me error "non-fast-forward" and when I want push branch "FixMenu" I must  pull master branch, at first and then I can push branch "Fix menu" with my changes.......
After I pull master branch  I had changes in NewsList and UpcommingMatches ()..... I noticed these changes, but I did not nothing with them, because it is not my changes now, but from past branches. So I compared these changes with the actual master, and  it was the same code as actual master, I left it that way

**Comment by buksy90** [comment]
okay, if you didnt do any changes in those files, then dont include them in commit :P ... when you use "git add ." to add files to index, you can then use gitk and check files and changes that have been added to index.
I will update your PR and remove unnecessary changes.

**Pull request merged**
